datasets:
  input_size: 512
  name: wireframe
  with_centermap_extend: false
decode:
  len_thresh: 5
  score_thresh: 0.05
  top_k: 500
loss:
  focal_loss_level: 0
  loss_type: 1*L1
  loss_weight_dict_list:
  - sol_center_loss: 1.0
    tp_center_loss: 10.0
  match_sap_thresh: 5.0
  with_focal_loss: true
  with_match_loss: false
  with_sol_loss: true
model:
  model_name: mobilev2_mlsd_large
  num_classes: 1
  with_deconv: true
sys:
  cpu: false
  gpus: 1
  num_workers: 0
train:
  adam_epsilon: 1.0e-06
  batch_size: 8
  cache_to_mem: false
  data_cache_dir: /Data/Line_Data/wireframe_cache/
  device_ids:
  - 0
  device_ids_str: '0'
  do_train: true
  dropout: 0.1
  early_stop_n: 200
  gradient_accumulation_steps: 1
  img_dir: /Data/sample_train/aug_save/image/
  label_fn: /Data/sample_train/aug_save/train_data.json
  learning_rate: 0.0003
  load_from: ''
  log_steps: 50
  lr_decay_gamma: 0.2
  milestones:
  - 50
  - 100
  - 150
  milestones_in_epo: true
  num_train_epochs: 100
  num_workers: 0
  save_dir: /needle_final/mlsd_test/weight_sample/baseline+loss+amse+msag+aug+hint
  use_step_lr_policy: true
  warmup_steps: 100
  weight_decay: 1.0e-06
  with_cache: false
val:
  batch_size: 8
  img_dir: /Data/sample_train/aug_save/image/
  label_fn: /Data/sample_train/aug_save/val_data.json
  val_after_epoch: -1
